<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        // 예외가 발생하지 않는 상황 
        try {
            const result = 10 + 20;
            console.log(result);
        } catch (exception) {
            console.log('1번째 catch 에서 예외 얻음');
        } finally {
            console.log('1번째 finally');
        }

        // 예외가 발생하느 상황
        try {
            willExcept.happy();
            console.log('2번째 코드 수행 완료');
        } catch (exception) {
            console.log('2번째 catch 에서 예외 얻음');
        } finally {
            console.log('2번째 finally');
        }
    </script>
</head>

<body>

</body>

</html>l